name: milktea
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.1
  go_router: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  dio: ^5.0.1
  riverpod: ^2.3.0
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/font/Oswald-Regular.ttf
        - asset: assets/font/Oswald-Light.ttf
          weight: 300
        - asset: assets/font/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Oswald-Medium.ttf
          weight: 500
        - asset: assets/font/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/font/Oswald-Bold.ttf
          weight: 700